module.exports = {
	APStack: require("./APStack.js"),
	APWeb: require("./APWeb.js"),
	AttenuationMatrix: require("./AttenuationMatrix.js"),
	BandFilter: require("./BandFilter.js"),
	Boop: require("./Boop.js"),
	ComplexOrbit: require("./ComplexOrbit.js"),
	DelayMixer: require("./DelayMixer.js"),
	FrequencyGroup: require("./FrequencyGroup.js"),
	LFO: require("./LFO.js"),
	ManyOsc: require("./ManyOsc.js"),
	MidiOsc: require("./MidiOsc.js"),
	Mixer: require("./Mixer.js"),
	MultiTapDelay: require("./MultiTapDelay.js"),
	OrbittySine: require("./OrbittySine.js"),
	ScaryPatch: require("./ScaryPatch.js"),
	SineBoop: require("./SineBoop.js"),
	SineCloud: require("./SineCloud.js"),
	Space: require("./Space.js"),
	SpaceChannel: require("./SpaceChannel.js"),
	StereoDetune: require("./StereoDetune.js"),
	StereoOsc: require("./StereoOsc.js"),
	TriggerGroup: require("./TriggerGroup.js"),
	Worm: require("./Worm.js")
}